CREATE DATABASE QUIS;

USE QUIS;

CREATE TABLE USERS(
    userID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    userData BLOB
)ENGINE=InnoDB;

CREATE TABLE STUDYSETS(
    studysetID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    userID INT NOT NULL,
    studysetURL char(5) NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255),
    description varchar(255),
    terms BLOB,
    CONSTRAINT fk_user FOREIGN KEY (userID) REFERENCES USERS (USERID)
)ENGINE=InnoDB;